### PR TITLE
:green_heart: [api]: Add Dockerfile for api-evidence app #20

### PR DESCRIPTION
**Pull request by beefho67**
1. Add Dockerfile for api-evidence
2. Add a shell script that runs postgres and api-evidence from container
3. config dependencies for api-evidence

### CODE REVIEW

**Comment by solomondefi-dev** [comment]
Hey @kelvin-wong can you take a look at this to see if it works for you? We will remove postgres from the docker build eventually once it's set up in skaffold (or something like that), but for now it should be enough for testing and local dev.

**Comment by solomondefi-dev** [comment]
This looks good to me! But, you missed the underscore in `green_heart` 😁

**Comment by solomondefi-dev** [comment]
@beefho67 Based on discussion, the db stuff will be handled in skaffold, since we would need docker compose here to get it working correctly, and I don't want to add that now since it's temporary.

If this is ok with you, we can merge.

**Comment by beefho67** [comment]
> @beefho67 Based on discussion, the db stuff will be handled in skaffold, since we would need docker compose here to get it working correctly, and I don't want to add that now since it's temporary.
> 
> If this is ok with you, we can merge.

It looks good to me. I think we can merge the PR.

**Pull request merged**
