### PR TITLE
Common event json schema

### LINKED ISSUE #146: A common event type between TS and Py
Add some common event type definitions (maybe JSON) that we can generate TypeScript interfaces and Python classes from this.

### PR DESCRIPTION
**Pull request by apolkingg8**
Close #146

### CODE REVIEW

**Comment by apolkingg8** [comment]
Hi @kelvin-wong , I need your help to complete this PR: 

1. Please add a script to generate the JSON schema into `libs/shared/util-event/schema`, the file name should be `xxx.schema.json`.
2. Add the script into CI, before the `Generate event interface` step.

Thanks a lot :)

**Comment by solomondefi-dev** [comment]
One thing I want to note is that all generated files should be committed to the repository, unless they are in the root `/dist` folder.

**Comment by apolkingg8** [comment]
> One thing I want to note is that all generated files should be committed to the repository, unless they are in the root `/dist` folder.

Why? As far as I know, the generated files should be ignored in git, and re-generated when the source change (just kile what we do in the contract type). Isn't it?

**Comment by solomondefi-dev** [comment]
Hm, the contract types are already causing some trouble if the developer forgets to regenerate. I prefer for them to be included in the repo as well - it's nice to limit the number of steps between "git clone" and "run the project".

In general, generated files excluded from git should be considered build files, and should be generated to the root `/dist` folder. This is standard practice with Nx.

**Comment by apolkingg8** [comment]
If we add the generated files into git, that will also cause some sync issue if the developer forgets to regenerate from the source. I think the better way is to add a git hook and do the following steps:

1. check source changed or not
2. check type is empty or not
3. if changed or type is empty, regenerate files

Not surveyed it yet, but I think it's not so hard to implement. I don't think we should put every generated file into `/dist`, the project structure will be very weird if we do that.

**Comment by apolkingg8** [comment]
Open #160 for the generator hook.

**Comment by solomondefi-dev** [comment]
Hey @kelvin-wong, can you try adding the script to CI, so that it passes? If it's easier, you could implement the hook discussed in #159 at the same time.

**Comment by kelvin-wong** [comment]
> Hey @kelvin-wong, can you try adding the script to CI, so that it passes? If it's easier, you could implement the hook discussed in #159 at the same time.

OK. Let me look into it.

**Comment by solomondefi-dev** [comment]
@kelvin-wong @apolkingg8 Does it make sense to merge this now and cover CI problems in #159? I don't want this to get too stale and cause conflicts with other PRs.

**Comment by kelvin-wong** [comment]
The generation script is added to this pull request. I think my part is done here. My remaining work could continue on #159.

**Comment by apolkingg8** [comment]
Ok, I'll let the CI pass here and merge it.

**Comment by solomondefi-dev** [comment]
Nice work guys, thanks!

**Pull request merged**
